version: '3'

services:
  database:
    image: postgres
    volumes:
      - C:\Users\tjgon\www\api-sample\data\postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=apiSample